//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://companyname.gate", ConfigurationName="IAdmin")]
public interface IAdmin
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://companyname.gate/IAdmin/reloadContext", ReplyAction="http://companyname.gate/IAdmin/reloadContextResponse")]
    string reloadContext(string value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://companyname.gate/IAdmin/getMemory", ReplyAction="http://companyname.gate/IAdmin/getMemoryResponse")]
    string getMemory(string value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://companyname.gate/IAdmin/getConnections", ReplyAction="http://companyname.gate/IAdmin/getConnectionsResponse")]
    string getConnections(string value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://companyname.gate/IAdmin/getLog", ReplyAction="http://companyname.gate/IAdmin/getLogResponse")]
    string getLog(string value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://companyname.gate/IAdmin/EncryptData", ReplyAction="http://companyname.gate/IAdmin/EncryptDataResponse")]
    string EncryptData(string plainText);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://companyname.gate/IAdmin/DecryptData", ReplyAction="http://companyname.gate/IAdmin/DecryptDataResponse")]
    string DecryptData(string cipherText);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAdminChannel : IAdmin, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AdminClient : System.ServiceModel.ClientBase<IAdmin>, IAdmin
{
    
    public AdminClient()
    {
    }
    
    public AdminClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AdminClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string reloadContext(string value)
    {
        return base.Channel.reloadContext(value);
    }
    
    public string getMemory(string value)
    {
        return base.Channel.getMemory(value);
    }
    
    public string getConnections(string value)
    {
        return base.Channel.getConnections(value);
    }
    
    public string getLog(string value)
    {
        return base.Channel.getLog(value);
    }
    
    public string EncryptData(string plainText)
    {
        return base.Channel.EncryptData(plainText);
    }
    
    public string DecryptData(string cipherText)
    {
        return base.Channel.DecryptData(cipherText);
    }
}
